// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-sq4-AcbJeUeGEHXOsXt5RpTe1Nssxjk',
    appId: '1:38904835960:android:c2958921c14db8eb45228d',
    messagingSenderId: '38904835960',
    projectId: 'gear-max-admin',
    authDomain: 'gear-max-admin.firebaseapp.com',
    storageBucket: 'gear-max-admin.appspot.com',
    measurementId: 'G-55VVR3M7XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-sq4-AcbJeUeGEHXOsXt5RpTe1Nssxjk',
    appId: '1:38904835960:android:c2958921c14db8eb45228d',
    messagingSenderId: '38904835960',
    projectId: 'gear-max-admin',
    authDomain: 'gear-max-admin.firebaseapp.com',
    storageBucket: 'gear-max-admin.appspot.com',
    measurementId: 'G-55VVR3M7XH',
  );
}
