// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYkMFi-o9FHtssOUeTGjbwn8En7yLrgOU',
    appId: '1:548971476814:android:2c439da8b81f8b0dbe501f',
    messagingSenderId: '548971476814',
    projectId: 'gear-max-84b8b',
    authDomain: 'gear-max-84b8b.firebaseapp.com',
    storageBucket: 'gear-max-84b8b.appspot.com',
    measurementId: 'G-55VVR3M7XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYkMFi-o9FHtssOUeTGjbwn8En7yLrgOU',
    appId: '1:548971476814:android:9ec39fd338a7aefabe501f',
    messagingSenderId: '548971476814',
    projectId: 'gear-max-84b8b',
    authDomain: 'gear-max-84b8b.firebaseapp.com',
    storageBucket: 'gear-max-84b8b.appspot.com',
    measurementId: 'G-55VVR3M7XH',
  );


}
